-- 코드를 입력하세요
-- 대여중, 대여기록, 자동차 종류 별 대여 기간 종류별 할인정책정보

-- FROM CAR_RENTAL_COMPANY_CAR A
-- JOIN  CAR_RENTAL_COMPANY_RENTAL_HISTORY B
-- JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C

WITH IRRENTALABLE AS (
    SELECT 
        CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE "2022-11" BETWEEN DATE_FORMAT(START_DATE, "%Y-%m") AND DATE_FORMAT(END_DATE, "%Y-%m")
    GROUP BY CAR_ID
        )

SELECT 
    A.CAR_ID,
    A.CAR_TYPE,
    ROUND(DAILY_FEE * 30 * (100-C.DISCOUNT_RATE)*0.01) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
INNER JOIN  CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON A.CAR_TYPE = C.CAR_TYPE AND DURATION_TYPE = "30일 이상"
WHERE A.CAR_ID NOT IN (SELECT CAR_ID FROM IRRENTALABLE)
AND A.CAR_TYPE IN ("SUV", "세단")
GROUP BY A.CAR_ID
HAVING FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC