WITH MOST_FAVORITES AS (
    SELECT
        FOOD_TYPE,
        MAX(FAVORITES) AS MAX
    FROM 
        REST_INFO
    GROUP BY FOOD_TYPE

)

SELECT
    A.FOOD_TYPE,
    A.REST_ID,
    A.REST_NAME,
    A.FAVORITES
FROM REST_INFO A
INNER JOIN MOST_FAVORITES B ON A.FAVORITES = B.MAX AND A.FOOD_TYPE = B.FOOD_TYPE
ORDER BY 1 DESC
