-- 코드를 입력하세요
SELECT
    DATE_FORMAT(A.SALES_DATE, "%Y-%m-%d") as SALES_DATE,
    A.PRODUCT_ID,
    A.USER_ID,
    A.SALES_AMOUNT

FROM
(SELECT
    SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE BETWEEN "2022-03-01" AND "2022-03-31"
UNION
SELECT
    SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE BETWEEN "2022-03-01" AND "2022-03-31") A
ORDER BY A.SALES_DATE, A.PRODUCT_ID, A.USER_ID