-- 코드를 입력하세요
WITH MAX_ID AS (SELECT
    A.BOARD_ID
FROM USED_GOODS_BOARD A
INNER JOIN USED_GOODS_FILE B
ON A.BOARD_ID = B.BOARD_ID
ORDER BY VIEWS DESC
           LIMIT 1)
           
SELECT
    CONCAT("/home/grep/src/", X.BOARD_ID, "/", Y.FILE_ID, Y.FILE_NAME, Y.FILE_EXT) AS FILE_PATH
FROM MAX_ID X
INNER JOIN USED_GOODS_FILE Y
ON X.BOARD_ID = Y.BOARD_ID
ORDER BY Y.FILE_ID DESC