WITH MAX_TABLE AS (SELECT
    FOOD_TYPE,
    MAX(FAVORITES) AS FAVORS
FROM REST_INFO
GROUP BY FOOD_TYPE)

SELECT
    A.FOOD_TYPE,
    REST_ID,
    REST_NAME,
    A.FAVORITES
FROM REST_INFO A
INNER JOIN MAX_TABLE B ON A.FOOD_TYPE = B.FOOD_TYPE
WHERE A.FAVORITES = B.FAVORS
ORDER BY 1 DESC
