-- 코드를 입력하세요
SELECT
    U.USER_ID,
    U.NICKNAME,
    CONCAT(U.CITY, " ", STREET_ADDRESS1, " ", STREET_ADDRESS2) AS 전체주소,
    CONCAT(MID(U.TLNO, 1, 3), "-", MID(U.TLNO, 4, 4), "-", MID(U.TLNO, 8, 4)) AS 전화번호
FROM (
    SELECT * FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3    
) B
JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
ORDER BY 1 DESC