-- 코드를 입력하세요

WITH A AS (SELECT
    COUNT(MEMBER_ID) AS COUNT,
    MEMBER_ID
    -- MAX(COUNT(*)) AS COUNT
    

FROM REST_REVIEW
GROUP BY MEMBER_ID)


SELECT
    A.MEMBER_NAME,
    B.REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE A
INNER JOIN REST_REVIEW B
ON A.MEMBER_ID = B.MEMBER_ID
WHERE B.MEMBER_ID IN (SELECT 
    MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
HAVING COUNT(*) = (SELECT MAX(COUNT) FROM A))
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC
