WITH TEST AS (SELECT
    A.MEMBER_ID, COUNT(*)
FROM MEMBER_PROFILE A
INNER JOIN REST_REVIEW B
ON A.MEMBER_ID = B.MEMBER_ID
GROUP BY A.MEMBER_ID
ORDER BY 2 DESC
LIMIT 1)

SELECT
    B.MEMBER_NAME,
    A.REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM REST_REVIEW A
INNER JOIN MEMBER_PROFILE B
ON A.MEMBER_ID = B.MEMBER_ID
INNER JOIN TEST C
ON A.MEMBER_ID = C.MEMBER_ID
ORDER BY 3, 2