

SELECT
    A.CAR_ID,
    CASE 
        WHEN B.CAR_ID IS NULL THEN "대여 가능"
        ELSE "대여중"
    END AS AVAILABILTY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
LEFT OUTER JOIN (
    SELECT
        CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE "2022-10-16" BETWEEN START_DATE AND END_DATE
    GROUP BY CAR_ID
) B ON A.CAR_ID = B.CAR_ID
GROUP BY CAR_ID
ORDER BY 1 DESC;