-- DATEDIFF 케이스에 대해 어떻게 DURATION_TYPE과 연결시킬 수 있을까?
-- 
-- 

SELECT
    A.HISTORY_ID,
    ROUND(A.DAILY_FEE * A.DATEDIFF * (100-A.DISCOUNT_RATE) / 100) AS FEE
FROM (SELECT 
    HISTORY_ID,
    DATEDIFF(H.END_DATE, H.START_DATE)+1 AS DATEDIFF,
    C.DAILY_FEE,
    CASE
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 7 AND DATEDIFF(H.END_DATE, H.START_DATE)+1 <30 THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = "트럭" AND DURATION_TYPE="7일 이상")
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 30 AND DATEDIFF(H.END_DATE, H.START_DATE)+1 < 90 THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = "트럭" AND DURATION_TYPE= "30일 이상")
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 90 THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = "트럭" AND DURATION_TYPE="90일 이상")
    ELSE 0
    END AS DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_CAR C
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = "트럭") A
ORDER BY 2 DESC, 1 DESC