-- 코드를 입력하세요
WITH RECURSIVE HOURS AS (
    SELECT
        0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM HOURS
    WHERE HOUR < 23
) 

SELECT H.HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS A
RIGHT OUTER JOIN HOURS H ON H.HOUR = HOUR(A.DATETIME)
GROUP BY H.HOUR
    