-- 코드를 입력하세요
WITH A AS (SELECT
          * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
           WHERE CAR_TYPE = "트럭"
          )
SELECT 
    HISTORY_ID,
    IF(TEST.DURATION_TYPE = "할인없음", DAILY_FEE * DAYS, ROUND( DAILY_FEE * DAYS * (100 - discount_rate) * 0.01, 0)) AS FEE

FROM
(SELECT
    HISTORY_ID, DAILY_FEE, DATEDIFF(B.END_DATE, B.START_DATE)+1 AS DAYS,
    CASE
        WHEN DATEDIFF(B.END_DATE, B.START_DATE)+1 >= 90 THEN "90일 이상"
        WHEN DATEDIFF(B.END_DATE, B.START_DATE)+1 >= 30 THEN "30일 이상"
        WHEN DATEDIFF(B.END_DATE, B.START_DATE)+1 >= 7 THEN "7일 이상"
        ELSE "할인없음"
    END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR A
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID = B.CAR_ID
WHERE A.CAR_TYPE = "트럭") TEST
LEFT OUTER JOIN A
ON A.DURATION_TYPE = TEST.DURATION_TYPE
ORDER BY 2 DESC, 1 DESC