-- 코드를 입력하세요
SELECT
    
    date_format(DATETIME, "%H") AS HOUR,
    COUNT(ANIMAL_ID) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY date_format(DATETIME, "%H")
    HAVING HOUR BETWEEN 9 AND 19
    ORDER BY HOUR ASC