-- 코드를 작성해주세요
SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    MT.MAX_VAL - SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM ECOLI_DATA A
INNER JOIN (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_VAL
    FROM ECOLI_DATA GROUP BY YEAR
) MT ON YEAR(A.DIFFERENTIATION_DATE) = MT.YEAR
ORDER BY 1, 2