-- 코드를 작성해주세요

SELECT
    ID,
    TEST.FISH_NAME,
    TEST.LENGTH
FROM FISH_INFO O
INNER JOIN  (SELECT
    MAX(B.FISH_TYPE) AS FISH_TYPE,
    MAX(B.FISH_NAME) AS FISH_NAME,
    MAX(LENGTH) AS LENGTH
FROM FISH_INFO A
INNER JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
GROUP BY A.FISH_TYPE) TEST
ON O.FISH_TYPE = TEST.FISH_TYPE AND O.LENGTH = TEST.LENGTH
ORDER BY ID